#!/usr/bin/env python
# coding: utf-8

# ## Note Book Fix
# 
# New notebook

# # Exploratory Data Analysis (EDA)

# ## Karakteristik Data Populasi

# In[3]:


#EDA (Exploratory Data Analysis (EDA)
#Karakteristik  Data
import pandas as pd
import numpy as np

path = "/lakehouse/default/Files/populasi.xlsx" 




df_map = pd.read_excel(path, sheet_name="swk_kecamatan_map")
swk_kecamatan_map = df_map.groupby('SWK')['KECAMATAN'].apply(list).to_dict()

# Baca data populasi per kecamatan
df_pop_raw = pd.read_excel(path, sheet_name="populasi_kecamatan")
pop_data = dict(zip(df_pop_raw['KECAMATAN'], df_pop_raw['TOTAL_PENDUDUK']))

# Hitung total populasi per SWK
swk_pop = {
    swk: sum(pop_data.get(k, 0) for k in kecs)
    for swk, kecs in swk_kecamatan_map.items()
}
df_pop = pd.DataFrame(list(swk_pop.items()), columns=['SWK', 'total_penduduk'])
print(df_pop.to_string(index=False))


# ## Karakteristik Data Volume Sampah

# In[6]:


#EDA (Exploratory Data Analysis (EDA)
#Karakteristik  Data
import pandas as pd
import numpy as np

path = "/lakehouse/default/Files/volume-dummy2.xlsx" 

# Baca sheet pertama (default)
df = pd.read_excel(path)

print("="*60)
print("ANALISIS DATASET DARI FILE EXCEL")
print("="*60)

# 1. Informasi Dasar
print("\n📊 1. INFORMASI DASAR")
print("-"*40)
print(f"Nama File     : {path}")
print(f"Jumlah Baris  : {df.shape[0]:,}")
print(f"Jumlah Kolom  : {df.shape[1]}")
print(f"Total Sel     : {df.size:,}")

# 2. Preview Data
print("\n👀 2. PREVIEW DATA (5 baris pertama)")
print("-"*40)
print(df.head())

# 3. Tipe Data Setiap Kolom
print("\n📋 3. TIPE DATA PER KOLOM")
print("-"*40)
for col in df.columns:
    print(f"• {col:20s} : {df[col].dtype}")

# 4. Missing Value Analysis
print("\n🔍 4. MISSING VALUE ANALYSIS")
print("-"*40)
missing_count = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    'Kolom': df.columns,
    'Jumlah Missing': missing_count.values,
    'Persentase (%)': missing_percent.values
})

# Tampilkan hanya kolom yang memiliki missing value
missing_with_data = missing_df[missing_df['Jumlah Missing'] > 0]
if len(missing_with_data) > 0:
    print("Kolom dengan missing value:")
    print(missing_with_data.to_string(index=False))
    print(f"\nTotal Missing Value: {df.isnull().sum().sum():,} dari {df.size:,} sel")
    print(f"Persentase Missing : {df.isnull().sum().sum()/df.size*100:.2f}%")
else:
    print("✅ Tidak ada missing value dalam dataset")

# 5. Data Duplikat
print("\n🔄 5. DATA DUPLIKAT")
print("-"*40)
duplicate_count = df.duplicated().sum()
print(f"Jumlah baris duplikat: {duplicate_count:,}")

if duplicate_count > 0:
    duplicate_percent = (duplicate_count / len(df)) * 100
    print(f"Persentase duplikat : {duplicate_percent:.2f}%")
    
    # Tampilkan contoh data duplikat
    print("\nContoh data duplikat (5 baris pertama):")
    duplicate_rows = df[df.duplicated(keep='first')]
    print(duplicate_rows.head())
    
    # Tampilkan indeks baris yang duplikat
    duplicate_indices = df[df.duplicated(keep=False)].index.tolist()
    print(f"\nIndeks baris duplikat: {duplicate_indices[:10]}")
else:
    print("✅ Tidak ada data duplikat")

# 6. Statistik Ringkas (khusus kolom numerik)
print("\n📈 6. STATISTIK NUMERIK")
print("-"*40)
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
if len(numeric_cols) > 0:
    print("Statistik untuk kolom numerik:")
    print(df[numeric_cols].describe())
else:
    print("Tidak ada kolom numerik dalam dataset")


# ## Clearing Data

# In[7]:


#Data Sampah Per SWK
df.columns = [
    'NO', 'SWK', 'NAMA_TPS',
    'INPUT', 'ANGKUT', 'DIOLAH', 'SISA',
    'POOL_SPBU', 'SPBU_TPS', 'TPS_TOL', 'TOL_TPA',
    'TOTAL_JARAK', 'TOTAL_JARAK_BULAT', 'ESTIMASI_WAKTU', 'KETERANGAN'
]
df['SWK'] = df['SWK'].str.strip()
print("DataFrame RAW setelah rename kolom:")
display(df)


# ### Clearing Data With Wrangler

# In[8]:


# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Replace missing values with the mean of each column in: 'SISA'
    df = df.fillna({'SISA': df['SISA'].mean()})
    # Filter rows based on column: 'SISA'
    df = df[(df['SISA'] > -26.73) & (df['SISA'] < 27.7)]
    # Replace missing values with the mean of each column in: 'DIOLAH'
    df = df.fillna({'DIOLAH': df['DIOLAH'].mean()})
    # Replace missing values with the mean of each column in: 'ANGKUT'
    df = df.fillna({'ANGKUT': df['ANGKUT'].mean()})
    # Replace missing values with the mean of each column in: 'INPUT'
    df = df.fillna({'INPUT': df['INPUT'].mean()})
    # Drop rows with missing data across all columns
    df = df.dropna()
    return df

df_clean = clean_data(df.copy())
display(df_clean)


# In[9]:


print("="*60)
print("ANALISIS DATASET DARI FILE EXCEL")
print("="*60)

# 1. Informasi Dasar
print("\n📊 1. INFORMASI DASAR")
print("-"*40)
print(f"Nama File     : {path}")
print(f"Jumlah Baris  : {df_clean.shape[0]:,}")
print(f"Jumlah Kolom  : {df_clean.shape[1]}")
print(f"Total Sel     : {df_clean.size:,}")

# 2. Preview Data
print("\n👀 2. PREVIEW DATA (5 baris pertama)")
print("-"*40)
print(df_clean.head())

# 3. Tipe Data Setiap Kolom
print("\n📋 3. TIPE DATA PER KOLOM")
print("-"*40)
for col in df_clean.columns:
    print(f"• {col:20s} : {df_clean[col].dtype}")

# 4. Missing Value Analysis
print("\n🔍 4. MISSING VALUE ANALYSIS")
print("-"*40)
missing_count = df_clean.isnull().sum()
missing_percent = (df_clean.isnull().sum() / len(df_clean)) * 100

missing_df = pd.DataFrame({
    'Kolom': df_clean.columns,
    'Jumlah Missing': missing_count.values,
    'Persentase (%)': missing_percent.values
})

# Tampilkan hanya kolom yang memiliki missing value
missing_with_data = missing_df[missing_df['Jumlah Missing'] > 0]
if len(missing_with_data) > 0:
    print("Kolom dengan missing value:")
    print(missing_with_data.to_string(index=False))
    print(f"\nTotal Missing Value: {df_clean.isnull().sum().sum():,} dari {df_clean.size:,} sel")
    print(f"Persentase Missing : {df_clean.isnull().sum().sum()/df_clean.size*100:.2f}%")
else:
    print("✅ Tidak ada missing value dalam dataset")

# 5. Data Duplikat
print("\n🔄 5. DATA DUPLIKAT")
print("-"*40)
duplicate_count = df_clean.duplicated().sum()
print(f"Jumlah baris duplikat: {duplicate_count:,}")

if duplicate_count > 0:
    duplicate_percent = (duplicate_count / len(df_clean)) * 100
    print(f"Persentase duplikat : {duplicate_percent:.2f}%")
    
    # Tampilkan contoh data duplikat
    print("\nContoh data duplikat (5 baris pertama):")
    duplicate_rows = df_clean[df_clean.duplicated(keep='first')]
    print(duplicate_rows.head())
    
    # Tampilkan indeks baris yang duplikat
    duplicate_indices = df_clean[df_clean.duplicated(keep=False)].index.tolist()
    print(f"\nIndeks baris duplikat: {duplicate_indices[:10]}... (menampilkan 10 pertama)")
else:
    print("✅ Tidak ada data duplikat")

# 6. Statistik Ringkas (khusus kolom numerik)
print("\n📈 6. STATISTIK NUMERIK")
print("-"*40)
numeric_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()
if len(numeric_cols) > 0:
    print("Statistik untuk kolom numerik:")
    print(df_clean[numeric_cols].describe())
else:
    print("Tidak ada kolom numerik dalam dataset")


# ##

# ## Aggregation Data

# In[10]:


df_swk = df_clean.groupby('SWK').agg(
    jumlah_tps    = ('NAMA_TPS',         'count'),
    total_input   = ('INPUT',             'sum'),
    total_angkut  = ('ANGKUT',            'sum'),
    total_diolah  = ('DIOLAH',            'sum'),
    total_sisa    = ('SISA',              'sum'),
    avg_jarak_km  = ('TOTAL_JARAK_BULAT', 'mean'),
    max_jarak_km  = ('TOTAL_JARAK_BULAT', 'max'),
    avg_waktu_jam = ('ESTIMASI_WAKTU',    'mean'),
).round(3).reset_index()

print(df_swk.to_string(index=False))


# ## Feature Engineering

# In[11]:


df = df_swk.merge(df_pop, on='SWK')

# F1: Volume sampah per kapita (m³/orang)
df['sampah_per_kapita'] = df['total_input'] / df['total_penduduk']

# F2: Rasio pengangkutan — proporsi sampah yang berhasil diangkut
df['rasio_angkut'] = df['total_angkut'] / df['total_input'].replace(0, np.nan)

# F3: Rasio pengolahan — proporsi dari yang diangkut, berhasil diolah
df['rasio_diolah'] = df['total_diolah'] / df['total_angkut'].replace(0, np.nan)

# F4: Rasio sisa — proporsi sampah yang tidak terangkut
df['rasio_sisa'] = df['total_sisa'] / df['total_input'].replace(0, np.nan)

# F5: Beban per TPS — rata-rata volume input per titik layanan
df['beban_per_tps'] = df['total_input'] / df['jumlah_tps']

# F6: Indeks jarak — jarak rata-rata dinormalisasi ke [0,1]
df['indeks_jarak'] = df['avg_jarak_km'] / df['avg_jarak_km'].max()

print(df[['SWK', 'sampah_per_kapita', 'rasio_angkut',
          'rasio_diolah', 'rasio_sisa', 'beban_per_tps',
          'indeks_jarak']].round(4).to_string(index=False))


# ## Waste Burden Index

# In[14]:


# Normalisasi fitur ke rentang [0,1] sebelum pembobotan
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['sampah_per_kapita_norm'] = scaler.fit_transform(df[['sampah_per_kapita']])
df['beban_per_tps_norm']     = scaler.fit_transform(df[['beban_per_tps']])
df['rasio_sisa_norm']        = scaler.fit_transform(df[['rasio_sisa']])

# WBI: skor komposit — semakin tinggi = semakin berat beban pengelolaan
# Bobot: rasio_sisa(0.35) + sampah_per_kapita(0.25) + indeks_jarak(0.20) + beban_per_tps(0.20)
df['WBI'] = (
    0.35 * df['rasio_sisa_norm'] +
    0.25 * df['sampah_per_kapita_norm'] +
    0.20 * df['indeks_jarak'] +
    0.20 * df['beban_per_tps_norm']
)
df.fillna(0, inplace=True)

print(df[['SWK', 'WBI']].sort_values('WBI', ascending=False).round(4).to_string(index=False))


# ## Labeling

# In[15]:


def label_wbi(wbi):
    if wbi >= 0.60:
        return 'KRITIS'
    elif wbi >= 0.30:
        return 'WASPADA'
    else:
        return 'AMAN'

df['LABEL'] = df['WBI'].apply(label_wbi)
print(df[['SWK', 'WBI', 'LABEL']].sort_values('WBI', ascending=False).round(4).to_string(index=False))
print(f"\nDistribusi label:\n{df['LABEL'].value_counts().to_string()}")


# ## Persiapan Label dan Fitur TPS
# 

# In[16]:


df_tps_feat = df_clean.copy()
df_tps_feat['INPUT']  = df_tps_feat['INPUT'].fillna(df_tps_feat['INPUT'].median())
df_tps_feat['ANGKUT'] = df_tps_feat['ANGKUT'].fillna(0)
df_tps_feat['DIOLAH'] = df_tps_feat['DIOLAH'].fillna(0)
df_tps_feat['SISA']   = df_tps_feat['SISA'].clip(lower=0).fillna(0)

# Hitung fitur per TPS
df_tps_feat['rasio_angkut'] = df_tps_feat['ANGKUT'] / df_tps_feat['INPUT'].replace(0, np.nan)
df_tps_feat['rasio_diolah'] = df_tps_feat['DIOLAH'] / df_tps_feat['ANGKUT'].replace(0, np.nan)
df_tps_feat['rasio_sisa']   = df_tps_feat['SISA']   / df_tps_feat['INPUT'].replace(0, np.nan)
df_tps_feat['indeks_jarak'] = (
    df_tps_feat['TOTAL_JARAK_BULAT'] / df_tps_feat['TOTAL_JARAK_BULAT'].max()
)
df_tps_feat.fillna(0, inplace=True)

# WBI per TPS — digunakan HANYA untuk membuat label, bukan fitur model
scaler2 = MinMaxScaler()
df_tps_feat['rasio_sisa_norm']   = scaler2.fit_transform(df_tps_feat[['rasio_sisa']])
df_tps_feat['rasio_angkut_norm'] = 1 - scaler2.fit_transform(df_tps_feat[['rasio_angkut']])
df_tps_feat['wbi_tps'] = (
    0.40 * df_tps_feat['rasio_sisa_norm'] +
    0.30 * df_tps_feat['rasio_angkut_norm'] +
    0.30 * df_tps_feat['indeks_jarak']
)
df_tps_feat['LABEL'] = df_tps_feat['wbi_tps'].apply(label_wbi)

print(f"Distribusi label level TPS:\n{df_tps_feat['LABEL'].value_counts().to_string()}")


# ## Pelatihan Model

# In[19]:


from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_validate, train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay
# Fitur model: wbi_tps TIDAK dimasukkan untuk mencegah label bug
X_feat = ['rasio_angkut', 'rasio_diolah', 'rasio_sisa', 'indeks_jarak']
X = df_tps_feat[X_feat].values
y = df_tps_feat['LABEL'].values

# Split Train/Test 80:20 — data test tidak pernah dilihat model saat training
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
print(f"Ukuran data  — Train: {len(X_train)}, Test: {len(X_test)}")

# Cross-Validation 5-fold pada data training
model = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')
cv    = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

cv_results = cross_validate(
    model, X_train, y_train, cv=cv,
    scoring=['f1_weighted', 'accuracy'],
    return_train_score=True
)

print(f"\nCross-Validation (5-fold) pada Data Training:")
print(f"  Train Accuracy : {cv_results['train_accuracy'].mean():.4f} ± {cv_results['train_accuracy'].std():.4f}")
print(f"  Val   Accuracy : {cv_results['test_accuracy'].mean():.4f}  ± {cv_results['test_accuracy'].std():.4f}")
print(f"  Train F1-Score : {cv_results['train_f1_weighted'].mean():.4f} ± {cv_results['train_f1_weighted'].std():.4f}")
print(f"  Val   F1-Score : {cv_results['test_f1_weighted'].mean():.4f}  ± {cv_results['test_f1_weighted'].std():.4f}")

gap_acc = cv_results['train_accuracy'].mean() - cv_results['test_accuracy'].mean()
gap_f1  = cv_results['train_f1_weighted'].mean() - cv_results['test_f1_weighted'].mean()
print(f"\n  Gap Accuracy (Train−Val) : {gap_acc:.4f}")
print(f"  Gap F1-Score (Train−Val) : {gap_f1:.4f}")
if gap_acc > 0.10:
    print("  ⚠️  Gap > 0.10 — indikasi overfitting")
else:
    print("  ✅  Gap dalam batas wajar — model generalisasi baik")

# Fit final model & evaluasi pada Test Set
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(f"\nEvaluasi pada Test Set (data yang tidak pernah dilihat model):")
print(classification_report(y_test, y_pred, zero_division=0))

feat_imp = pd.Series(model.feature_importances_, index=X_feat).sort_values(ascending=False)
print(f"Feature Importance:\n{feat_imp.round(4).to_string()}")


# ## Evaluasi Model

# In[20]:


# print(f"Cross-Validation (5-fold) Results:")
# print(f"  Accuracy  : {cv_results['test_accuracy'].mean():.4f} ± {cv_results['test_accuracy'].std():.4f}")
# print(f"  F1-Score  : {cv_results['test_f1_weighted'].mean():.4f} ± {cv_results['test_f1_weighted'].std():.4f}")


# model.fit(X, y)
# y_pred = model.predict(X)
# print(f"\nClassification Report (train):\n{classification_report(y, y_pred)}")


# feat_imp = pd.Series(model.feature_importances_, index=X_feat).sort_values(ascending=False)
# print(f"Feature Importance:\n{feat_imp.round(4)}")
import mlflow
import mlflow.sklearn
from mlflow.models.signature import infer_signature

# Start MLflow run
with mlflow.start_run(run_name="classification_model_v1"):
    
    # Fit model
    model.fit(X, y)
    y_pred = model.predict(X)
    
    # Log metrics
    mlflow.log_metric("cv_accuracy_mean", cv_results['test_accuracy'].mean())
    mlflow.log_metric("cv_accuracy_std", cv_results['test_accuracy'].std())
    mlflow.log_metric("cv_f1_mean", cv_results['test_f1_weighted'].mean())
    
    # Log model
    signature = infer_signature(X, y_pred)
    mlflow.sklearn.log_model(
        sk_model=model,
        artifact_path="model",
        signature=signature,
        registered_model_name="my_classification_model"  # nama model di registry
    )
    
    print("Model berhasil di-log ke MLflow!")


# ## Output WBI

# In[27]:


output = df[['SWK', 'jumlah_tps', 'total_penduduk', 'total_input',
             'total_angkut', 'total_sisa', 'rasio_sisa', 'rasio_angkut',
             'sampah_per_kapita', 'avg_jarak_km', 'WBI', 'LABEL']].copy()
output = output.sort_values('WBI', ascending=False).reset_index(drop=True)
output.index += 1

print(output.round(4).to_string())


# ## Visualisasi

# In[28]:


import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
COLOR_MAP = {'KRITIS': '#E74C3C', 'WASPADA': '#F39C12', 'AMAN': '#27AE60'}

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('Analisis Klasifikasi Pengelolaan Sampah Kota Bandung',
             fontsize=14, fontweight='bold')

# ── Plot 1: WBI per SWK ─────────────────────────────────────────────────────
ax1 = axes[0]
df_sorted = df.sort_values('WBI', ascending=False)
bar_colors = [COLOR_MAP[l] for l in df_sorted['LABEL']]

bars = ax1.barh(df_sorted['SWK'], df_sorted['WBI'], color=bar_colors, edgecolor='white')
ax1.axvline(0.60, color='#E74C3C', linestyle='--', linewidth=1.2, label='Batas KRITIS (0.60)')
ax1.axvline(0.30, color='#F39C12', linestyle='--', linewidth=1.2, label='Batas WASPADA (0.30)')
ax1.set_xlabel('Waste Burden Index (WBI)')
ax1.set_title('WBI per Satuan Wilayah Kerja (SWK)')
ax1.legend(fontsize=8)

for bar, val in zip(bars, df_sorted['WBI']):
    ax1.text(val + 0.005, bar.get_y() + bar.get_height() / 2,
             f'{val:.3f}', va='center', fontsize=9)

# ── Plot 2: Distribusi Label SWK ─────────────────────────────────────────────
ax2 = axes[1]
label_counts = df['LABEL'].value_counts()
wedge_colors = [COLOR_MAP[l] for l in label_counts.index]

wedges, texts, autotexts = ax2.pie(
    label_counts.values,
    labels=label_counts.index,
    colors=wedge_colors,
    autopct='%1.0f%%',
    startangle=90,
    wedgeprops=dict(edgecolor='white', linewidth=2)
)

for t in autotexts:
    t.set_fontsize(11)
    t.set_fontweight('bold')

ax2.set_title('Distribusi Klasifikasi SWK')

plt.tight_layout()
plt.savefig('visualisasi_sampah_bandung.png', dpi=150, bbox_inches='tight')
plt.show()


# ## Insight

# In[29]:


kritis = output[output['LABEL'] == 'KRITIS']['SWK'].tolist()
waspada = output[output['LABEL'] == 'WASPADA']['SWK'].tolist()
aman = output[output['LABEL'] == 'AMAN']['SWK'].tolist()

print(f"🔴 KRITIS  : {kritis}")
print(f"🟡 WASPADA : {waspada}")
print(f"🟢 AMAN    : {aman}")

print("\n📊 Top Issues per SWK:")
for _, row in output.iterrows():
    issues = []
    if row['rasio_sisa'] > 0.3:
        issues.append(f"sisa tinggi ({row['rasio_sisa']:.0%})")
    if row['rasio_angkut'] < 0.7:
        issues.append(f"angkut rendah ({row['rasio_angkut']:.0%})")
    if row['sampah_per_kapita'] > output['sampah_per_kapita'].median():
        issues.append(f"sampah/kapita di atas median")
    if row['avg_jarak_km'] > 70:
        issues.append(f"jarak TPA jauh ({row['avg_jarak_km']:.0f} km)")

    label_icon = {'KRITIS': '🔴', 'WASPADA': '🟡', 'AMAN': '🟢'}[row['LABEL']]

    # Add a specific explanation for WASPADA/KRITIS areas that don't have other flagged issues
    if not issues and row['LABEL'] == 'WASPADA':
        issues.append(f"WBI mendekati batas KRITIS ({row['WBI']:.2f}) tanpa isu spesifik teridentifikasi. Perlu penyelidikan lebih lanjut.")
    elif not issues and row['LABEL'] == 'KRITIS':
        issues.append(f"WBI sangat tinggi ({row['WBI']:.2f}) tanpa isu spesifik teridentifikasi. Perlu penyelidikan lebih lanjut.")
    elif not issues: # For AMAN areas or if no issues found for others
        issues.append('performa baik')

    print(f"  {label_icon} {row['SWK']}: {', '.join(issues)}")


# In[1]:


import mlflow
import mlflow.sklearn
from mlflow.models.signature import infer_signature

# Start MLflow run
with mlflow.start_run(run_name="classification_model_v1"):
    
    # Fit model
    model.fit(X, y)
    y_pred = model.predict(X)
    
    # Log metrics
    mlflow.log_metric("cv_accuracy_mean", cv_results['test_accuracy'].mean())
    mlflow.log_metric("cv_accuracy_std", cv_results['test_accuracy'].std())
    mlflow.log_metric("cv_f1_mean", cv_results['test_f1_weighted'].mean())
    
    # Log model
    signature = infer_signature(X, y_pred)
    mlflow.sklearn.log_model(
        sk_model=model,
        artifact_path="model",
        signature=signature,
        registered_model_name="my_classification_model"  # nama model di registry
    )
    
    print("Model berhasil di-log ke MLflow!")

